name: Retrain Model

on:
  push:
    paths:
      - 'retraining/copyright_data/**'  # Trigger action when a file is pushed to the copyright_data folder

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd retraining  # Navigate to the retrain directory
          python -m pip install --upgrade pip
          pip install spacy==3.5.1
          pip install -r requirements.txt

      - name: Run retraining script
        run: |
          cd retraining  # Ensure we are in the retrain directory
          python retrain_sgd_model.py

      - name: Upload model artifacts
        uses: actions/upload-artifact@v3
        with:
          name: retrained-model
          path: retrain/models/
